# Projeto 5: Classificação binária brest cancer - Carregar o classificador

## Etapa 1: Importação das Bibliotecas

In [1]:
!pip install torch==1.4.0

In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
torch.__version__

'1.4.0'

## Etapa 2: Base de dados

In [3]:
np.random.seed(123)
torch.manual_seed(123)

In [4]:
class cls_torch(nn.Module):

  def __init__(self):
    super().__init__()

    # 30 -> 16 -> 16 -> 1                       ARQUITETURA DA REDE
    self.dense0 = nn.Linear(30,8)               # Ligação das entradas com a 1ª camada de neurônios

    # Mesmos parâmetors usados pelo kernel initializer do Keras [https://keras.io/initializers/, ver sessão RandomNormal]
    torch.nn.init.normal_(self.dense0.weight,
                          mean=0.0, std = 0.05) # Inicializa os pesos com uma distribuição estatística uniforme
    
    self.dense1 = nn.Linear(8,8)                # Ligação da 1º camada com a 2º camada de neurônios
    torch.nn.init.normal_(self.dense1.weight,
                          mean=0.0, std = 0.05) # Inicializa os pesos com uma distribuição estatística uniforme
    self.activation = nn.ReLU()                 # Função de ativação da 2ª camada
    
    self.dense2 = nn.Linear(8,1)                # Ligação da 2º camada com a camada de saída
    self.dropout = nn.Dropout(0.2)
    self.output = nn.Sigmoid()                  # Função de ativação da 3ª camada (Output)

  def forward(self, X):
    """
    Recebe as entradas e faz a transmição de uma camada para outra até a saída
    :param X: Entrada no formato Numpy Array
    :return: Saída das previsões (Probabilidades)
    """
    X = self.dense0(X)
    X = self.activation(X)
    X = self.dropout(X)
    X = self.dense1(X)
    X = self.activation(X)
    X = self.dropout(X)
    X = self.dense2(X)
    X = self.output(X)
    return X

In [5]:
cls = cls_torch()

In [6]:
state_dict = torch.load('/content/cls_breast_cancer.pth')

In [7]:
state_dict

OrderedDict([('dense0.weight',
              tensor([[-6.2938e-01, -6.3880e-02, -3.8812e-01, -1.0131e-01,  5.3613e-02,
                       -5.2737e-02,  5.9786e-02, -6.1688e-02,  2.9235e-02,  8.3439e-02,
                        5.2361e-04,  1.0154e-03,  6.2317e-04, -1.3866e-03,  1.9200e-02,
                        1.1764e-01, -3.8250e-01, -2.6600e-01, -6.0280e-03,  4.2274e-01,
                       -4.7407e-01, -3.1142e-02, -3.2840e-01,  1.8073e-01,  4.6571e-02,
                        4.2041e-02,  2.2236e-02,  4.5930e-02,  3.1673e-02,  6.3382e-01],
                      [ 8.2932e-02,  1.6685e-02,  5.3594e-02, -5.2358e-02,  8.3542e-02,
                       -2.1864e-04,  4.8437e-02, -1.6590e-03, -7.1115e-02, -2.8024e-02,
                        1.3979e-02, -1.1546e-02, -4.8893e-02,  1.0772e-01, -1.0195e-14,
                        1.0536e-04,  1.7714e-02, -3.6042e-13, -3.3771e-03, -4.1130e-14,
                       -5.3232e-02,  4.5065e-02, -4.9866e-02, -6.6553e-02, -8.3494e-02,


In [8]:
cls.load_state_dict(state_dict)

<All keys matched successfully>

## Etapa 3: Previsões

In [9]:
novo = torch.tensor([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                  0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                  0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                  0.84, 158, 0.363]], dtype = torch.float)

In [12]:
cls.eval()
previsao = cls(novo)
previsao = (previsao.detach().numpy() > 0.5)
previsao

array([[ True]])

In [13]:
previsores = pd.read_csv('/content/entradas_breast.csv')
classes = pd.read_csv('/content/saidas_breast.csv')

In [14]:
previsores = torch.tensor(np.array(previsores), dtype = torch.float)
classes = torch.tensor(np.array(classes), dtype = torch.float)

In [15]:
previsoes = cls.forward(previsores).detach()
previsoes

tensor([[3.3624e-09],
        [3.0390e-06],
        [1.5145e-04],
        [3.5194e-06],
        [2.2234e-03],
        [4.7528e-01],
        [1.4094e-06],
        [1.3330e-01],
        [2.5540e-01],
        [1.8320e-03],
        [4.2397e-02],
        [8.5288e-04],
        [9.9827e-02],
        [8.8744e-01],
        [8.8744e-01],
        [3.5808e-01],
        [5.0096e-03],
        [3.0901e-04],
        [4.2124e-11],
        [8.9949e-01],
        [8.8744e-01],
        [1.0000e+00],
        [3.0697e-01],
        [1.4131e-11],
        [1.2919e-11],
        [6.7497e-05],
        [3.5849e-01],
        [5.9923e-03],
        [1.7780e-04],
        [1.0012e-01],
        [1.0846e-04],
        [1.5637e-02],
        [2.1437e-03],
        [1.6319e-06],
        [5.0770e-04],
        [3.2573e-02],
        [8.3584e-01],
        [9.9843e-01],
        [7.8532e-01],
        [5.6025e-01],
        [6.6390e-01],
        [8.8744e-01],
        [4.0303e-06],
        [7.4666e-02],
        [7.9646e-01],
        [1

In [18]:
F.binary_cross_entropy(previsoes, classes).numpy()

array(0.16732664, dtype=float32)

In [19]:
accuracy_score(classes.numpy(), (previsoes > 0.5).numpy())

0.9420035149384886