# Medidas de dispersão

In [1]:
import math
import numpy as np
import pandas as pd
from scipy import stats, ndimage
import statistics as st

In [2]:
data = np.array([160, 165, 167, 164, 160, 166, 160, 161, 150, 152,
                 173, 160, 155, 164, 168, 162, 161, 168, 163, 156,
                 155, 169, 151, 170, 164, 155, 152, 163, 160, 155,
                 157, 156, 158, 158, 161, 154, 161, 156, 172, 153])

## Amplitude total e diferença interquartil

In [3]:
# Amplitude (h)
h = data.max() - data.min()
h

23

In [4]:
q1 = np.quantile(data, 0.25)
q3 = np.quantile(data, 0.75)
q1, q3

(155.75, 164.0)

In [5]:
# DIferença interquartil (di)
di = q3 - q1
di

8.25

In [6]:
# Outlier inferior
inf = q1 - (1.5 * di)
inf

143.375

In [7]:
# Outlier superior
sup = q3 + (1.5 * di)
sup

176.375

## Variância e desvio padrão

In [8]:
data_impar = np.array([150,151,152,152,153,154,155,155,155])

### Cálculo manual

In [9]:
media = data_impar.sum() / len(data_impar)
media

153.0

In [10]:
desvio = abs(data_impar - media)
desvio

array([3., 2., 1., 1., 0., 1., 2., 2., 2.])

In [11]:
desvio = desvio ** 2
desvio

array([9., 4., 1., 1., 0., 1., 4., 4., 4.])

In [12]:
soma_desvio = desvio.sum()
soma_desvio

28.0

In [13]:
v = soma_desvio / len(data_impar)
v

3.111111111111111

In [14]:
def get_variancia(data):
    media = data_impar.sum() / len(data_impar)
    desvio = abs(data_impar - media) ** 2
    soma_desvio = desvio.sum()
    return soma_desvio / len(data_impar)

In [15]:
get_variancia(data_impar)

3.111111111111111

In [16]:
from Models.Stats import Stats
cls_stats = Stats()
cls_stats.variance(data_impar)

3.111111111111111

In [17]:
cls_stats.std_deviation(data_impar)

1.7638342073763937

In [18]:
cls_stats.std_deviation(data)

5.829611908180509

In [19]:
cls_stats.coef_deviation(data_impar)

1.1528328152786886

In [20]:
cls_stats.coef_deviation(data)

3.634987939629312

### Bibliotecas

In [21]:
np.var(data_impar)

3.111111111111111

In [22]:
np.var(data)

33.984375

In [23]:
st.variance(data)

34

In [24]:
ndimage.variance(data)

33.984375

In [25]:
np.std(data_impar)

1.7638342073763937

In [26]:
np.std(data)

5.829611908180509

In [27]:
stats.tstd(data, ddof = 0)

5.829611908180509

In [28]:
stats.variation(data_impar) * 100

1.1528328152786886

In [29]:
stats.variation(data) * 100

3.634987939629312

In [30]:
cls_stats.df_stats(data)

inferior  superior  fi   xi  fi_xi    xi2  fi_xi2  Fi
gap                                                           
150-154       150       154   5  152    760  23104  115520   5
154-158       154       158   9  156   1404  24336  219024  14
158-162       158       162  11  160   1760  25600  281600  25
162-166       162       166   7  164   1148  26896  188272  32
166-170       166       170   5  168    840  28224  141120  37
170-174       170       174   3  172    516  29584   88752  40

In [31]:
data_impar

array([150, 151, 152, 152, 153, 154, 155, 155, 155])

In [32]:
cls_stats.df_stats(data_impar, h=2)

inferior  superior  fi   xi  fi_xi    xi2  fi_xi2  Fi
gap                                                           
150-152       150       152   2  151    302  22801   45602   2
152-154       152       154   3  153    459  23409   70227   5
154-156       154       156   4  155    620  24025   96100   9

In [33]:
df = cls_stats.df_stats(data)

In [34]:
std_dev = ((df.fi_xi2.sum() / df.fi.sum()) - (df.fi_xi.sum() / df.fi.sum()) ** 2) ** 0.5
std_dev

5.719265687131764

In [35]:
cls_stats.grp_std_deviation(df)

5.719265687131764