# Previsão de probabilidades em machine learning

In [1]:
import pandas as pd
import numpy as np

from sklearn.naive_bayes import GaussianNB

In [2]:
df = pd.read_csv('CSVs/credit_data.csv')
df.dropna(inplace=True)
df.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [3]:
X = df.iloc[:,1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [4]:
y = df.iloc[:,4].values
y

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [5]:
nb = GaussianNB()
nb.fit(X, y)

GaussianNB()

In [6]:
X[0], X[0].shape

(array([6.61559251e+04, 5.90170151e+01, 8.10653213e+03]), (3,))

In [7]:
X_new = X[0].reshape(1, -1)
X_new.shape

(1, 3)

In [8]:
nb.predict(X_new)

array([0], dtype=int64)

In [9]:
pred = nb.predict_proba(X_new)
pred

array([[1.00000000e+00, 2.03924534e-10]])

In [10]:
np.argmax(pred)

0

In [11]:
from Models.NaiveBayes import NaiveBayes
df.drop('i#clientid', axis=1,inplace=True)
df.columns = ['Receita', 'Idade', 'Divida', 'Target']
cls_nb = NaiveBayes(df, 'Target')

False


In [16]:
np.set_printoptions(suppress=True)
X_test = df.iloc[[0]][['Receita', 'Idade', 'Divida']].values[0]
list(X_test)

[66155.9250950813, 59.017015066929204, 8106.53213128514]

In [18]:
cls_nb.classify(list(X_test))

Classe   Receita       Idade    Divida     Total
Target      High        High      High     Proba
0       0.252042    0.291715  0.194282  0.858287
1       0.240283  0.00353357  0.590106  0.141713


{0: '99.42%', 1: '0.58%'}